<?php
namespace Features\Auth\Register;

use Features\Auth\Shared\Ports\UserRepositoryInterface;
use Features\Auth\Shared\Domain\User;
use Features\Auth\Shared\Exceptions\UserAlreadyExistsException;

class RegisterHandler
{
    private UserRepositoryInterface $repository;

    public function __construct(UserRepositoryInterface $repository)
    {
        $this->repository = $repository;
    }

    public function handle(RegisterCommand $command): array
    {
        // Check if email already exists
        if ($this->repository->emailExists($command->email)) {
            throw new UserAlreadyExistsException();
        }

        // Generate user ID using PostgreSQL's gen_random_uuid()
        // The repository will handle UUID generation in the INSERT query
        $userId = ''; // This will be generated by the database

        // Create user domain object with hashed password
        $user = User::create($userId, $command->name, $command->email, $command->password);

        // Save user to database
        $this->repository->create($user);

        // Fetch the created user to get the actual UUID from database
        $createdUser = $this->repository->findByEmail($command->email);

        if (!$createdUser) {
            throw new \RuntimeException('Failed to create user');
        }

        // Generate verification code (10 characters, alphanumeric)
        $code = substr(str_shuffle('ABCDEFGHJKLMNPQRSTUVWXYZ23456789'), 0, 10);
        $expiresAt = new \DateTime('+24 hours');

        // Save verification code
        $this->repository->saveVerificationCode($createdUser->getId(), $code, $expiresAt);

        // Return user data without password and the verification code
        return [
            'user' => [
                'id' => $createdUser->getId(),
                'name' => $createdUser->getName(),
                'email' => $createdUser->getEmail()
            ],
            'verification_code' => $code, // For development/testing - remove in production
            'message' => 'Registration successful. Please verify your email.'
        ];
    }
}
